--------------------------------------------------------
--  File created - Friday-July-05-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence MENU_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SHA"."MENU_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STAFF_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SHA"."STAFF_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 26 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table FULLTIME
--------------------------------------------------------

  CREATE TABLE "SHA"."FULLTIME" 
   (	"STAFF_ID" NUMBER(*,0), 
	"MONTHLY_WAGE" NUMBER(38,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INVOICE
--------------------------------------------------------

  CREATE TABLE "SHA"."INVOICE" 
   (	"INVOICE_ID" NUMBER(*,0), 
	"INVOICEDATE" DATE, 
	"TOTALPRICE" NUMBER(38,2), 
	"ORDER_ID" NUMBER(*,0), 
	"STAFF_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "SHA"."MENU" 
   (	"MENU_ID" NUMBER(*,0), 
	"MENUNAME" VARCHAR2(255 BYTE), 
	"MENUTYPE" VARCHAR2(255 BYTE), 
	"MENUPRICE" NUMBER(38,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ODER
--------------------------------------------------------

  CREATE TABLE "SHA"."ODER" 
   (	"ORDER_ID" NUMBER(*,0), 
	"ORDERDATE" DATE, 
	"ORDERQUANTITY" NUMBER(*,0), 
	"ORDERTOTALAMOUNT" NUMBER(38,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDER_DETAILS
--------------------------------------------------------

  CREATE TABLE "SHA"."ORDER_DETAILS" 
   (	"ORDER_ID" NUMBER(*,0), 
	"MENU_ID" NUMBER(*,0), 
	"QUANTITY" NUMBER(*,0), 
	"AMOUNT" NUMBER(38,2), 
	"CUSTOMER_REMARK" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARTTIME
--------------------------------------------------------

  CREATE TABLE "SHA"."PARTTIME" 
   (	"STAFF_ID" NUMBER(*,0), 
	"HOURLY_WAGE" NUMBER(38,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STAFF
--------------------------------------------------------

  CREATE TABLE "SHA"."STAFF" 
   (	"STAFF_ID" NUMBER(*,0), 
	"STAFFNAME" VARCHAR2(255 BYTE), 
	"STAFFADDRESS" VARCHAR2(255 BYTE), 
	"STAFFPNUM" VARCHAR2(20 BYTE), 
	"STAFFGENDER" VARCHAR2(10 BYTE), 
	"SUPERVISOR_ID" NUMBER(*,0), 
	"STAFF_TYPE" VARCHAR2(255 BYTE), 
	"STAFFUNAME" VARCHAR2(255 BYTE), 
	"STAFFPASS" VARCHAR2(255 BYTE), 
	"STAFF_ROLES" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SHA.FULLTIME
SET DEFINE OFF;
Insert into SHA.FULLTIME (STAFF_ID,MONTHLY_WAGE) values (1,3000);
Insert into SHA.FULLTIME (STAFF_ID,MONTHLY_WAGE) values (2,2000);
Insert into SHA.FULLTIME (STAFF_ID,MONTHLY_WAGE) values (4,2000);
REM INSERTING into SHA.INVOICE
SET DEFINE OFF;
REM INSERTING into SHA.MENU
SET DEFINE OFF;
Insert into SHA.MENU (MENU_ID,MENUNAME,MENUTYPE,MENUPRICE) values (2,'Nasi Putih','FOOD',1);
Insert into SHA.MENU (MENU_ID,MENUNAME,MENUTYPE,MENUPRICE) values (3,'Ayam Masak Merah','FOOD',4);
Insert into SHA.MENU (MENU_ID,MENUNAME,MENUTYPE,MENUPRICE) values (4,'Ayam Masak Kicap','FOOD',4);
Insert into SHA.MENU (MENU_ID,MENUNAME,MENUTYPE,MENUPRICE) values (5,'Ikan Keli Masak Belado','FOOD',4);
Insert into SHA.MENU (MENU_ID,MENUNAME,MENUTYPE,MENUPRICE) values (6,'Telur Dadar','FOOD',1.5);
Insert into SHA.MENU (MENU_ID,MENUNAME,MENUTYPE,MENUPRICE) values (7,'Sosej','FOOD',0.5);
Insert into SHA.MENU (MENU_ID,MENUNAME,MENUTYPE,MENUPRICE) values (8,'Daging Masak Hitam','FOOD',6);
Insert into SHA.MENU (MENU_ID,MENUNAME,MENUTYPE,MENUPRICE) values (9,'Sambal Paru','FOOD',6);
Insert into SHA.MENU (MENU_ID,MENUNAME,MENUTYPE,MENUPRICE) values (10,'Vanilla Blue','BEVERAGES',3);
Insert into SHA.MENU (MENU_ID,MENUNAME,MENUTYPE,MENUPRICE) values (11,'Teh Ais','BEVERAGES',3);
Insert into SHA.MENU (MENU_ID,MENUNAME,MENUTYPE,MENUPRICE) values (12,'Sirap Ais','BEVERAGES',2);
Insert into SHA.MENU (MENU_ID,MENUNAME,MENUTYPE,MENUPRICE) values (13,'Lemon Soda','BEVERAGES',3);
Insert into SHA.MENU (MENU_ID,MENUNAME,MENUTYPE,MENUPRICE) values (14,'Ais Kosong ','BEVERAGES',0.5);
REM INSERTING into SHA.ODER
SET DEFINE OFF;
REM INSERTING into SHA.ORDER_DETAILS
SET DEFINE OFF;
REM INSERTING into SHA.PARTTIME
SET DEFINE OFF;
Insert into SHA.PARTTIME (STAFF_ID,HOURLY_WAGE) values (3,60);
Insert into SHA.PARTTIME (STAFF_ID,HOURLY_WAGE) values (5,60);
Insert into SHA.PARTTIME (STAFF_ID,HOURLY_WAGE) values (6,60);
REM INSERTING into SHA.STAFF
SET DEFINE OFF;
Insert into SHA.STAFF (STAFF_ID,STAFFNAME,STAFFADDRESS,STAFFPNUM,STAFFGENDER,SUPERVISOR_ID,STAFF_TYPE,STAFFUNAME,STAFFPASS,STAFF_ROLES) values (1,'Anas Munzir bin Lokman','25 Jalan Masjid India, Kuala Lumpur','014-8765432','Male',null,'FULLTIME','munzir','munzir123','Manager');
Insert into SHA.STAFF (STAFF_ID,STAFFNAME,STAFFADDRESS,STAFFPNUM,STAFFGENDER,SUPERVISOR_ID,STAFF_TYPE,STAFFUNAME,STAFFPASS,STAFF_ROLES) values (2,'Ahmad bin Ismail','12 Jalan Perdana, Kuala Lumpur','012-3456789','Male',1,'FULLTIME','ahmadismail','ahmadhensem','Worker');
Insert into SHA.STAFF (STAFF_ID,STAFFNAME,STAFFADDRESS,STAFFPNUM,STAFFGENDER,SUPERVISOR_ID,STAFF_TYPE,STAFFUNAME,STAFFPASS,STAFF_ROLES) values (3,'Siti binti Mahmud','45 Jalan Raja Chulan, Kuala Lumpur','017-9876543','Female',1,'PARTTIME','sitimahmud','siti123','Worker');
Insert into SHA.STAFF (STAFF_ID,STAFFNAME,STAFFADDRESS,STAFFPNUM,STAFFGENDER,SUPERVISOR_ID,STAFF_TYPE,STAFFUNAME,STAFFPASS,STAFF_ROLES) values (4,'Muhammad bin Hassan','30 Jalan Bukit Bintang, Kuala Lumpur','016-8765432','Male',1,'FULLTIME','mamat','mamat12345','Assistant Manager');
Insert into SHA.STAFF (STAFF_ID,STAFFNAME,STAFFADDRESS,STAFFPNUM,STAFFGENDER,SUPERVISOR_ID,STAFF_TYPE,STAFFUNAME,STAFFPASS,STAFF_ROLES) values (5,'Nor binti Abdullah','8 Jalan Sultan Ismail, Kuala Lumpur','013-6543210','Female',1,'PARTTIME','nornor','nor123','Worker');
Insert into SHA.STAFF (STAFF_ID,STAFFNAME,STAFFADDRESS,STAFFPNUM,STAFFGENDER,SUPERVISOR_ID,STAFF_TYPE,STAFFUNAME,STAFFPASS,STAFF_ROLES) values (6,'Nurul binti Ahmad','15 Jalan Ampang, Kuala Lumpur','019-1234567','Female',1,'PARTTIME','nurul@','nurul123','Worker');
Insert into SHA.STAFF (STAFF_ID,STAFFNAME,STAFFADDRESS,STAFFPNUM,STAFFGENDER,SUPERVISOR_ID,STAFF_TYPE,STAFFUNAME,STAFFPASS,STAFF_ROLES) values (7,'test1234','north usa 1234','012345678890','Male',1,'Worker','test1234','qwert',null);
--------------------------------------------------------
--  Constraints for Table INVOICE
--------------------------------------------------------

  ALTER TABLE "SHA"."INVOICE" ADD PRIMARY KEY ("INVOICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "SHA"."MENU" ADD PRIMARY KEY ("MENU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "SHA"."STAFF" ADD PRIMARY KEY ("STAFF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ODER
--------------------------------------------------------

  ALTER TABLE "SHA"."ODER" ADD PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FULLTIME
--------------------------------------------------------

  ALTER TABLE "SHA"."FULLTIME" ADD PRIMARY KEY ("STAFF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PARTTIME
--------------------------------------------------------

  ALTER TABLE "SHA"."PARTTIME" ADD PRIMARY KEY ("STAFF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FULLTIME
--------------------------------------------------------

  ALTER TABLE "SHA"."FULLTIME" ADD FOREIGN KEY ("STAFF_ID")
	  REFERENCES "SHA"."STAFF" ("STAFF_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVOICE
--------------------------------------------------------

  ALTER TABLE "SHA"."INVOICE" ADD FOREIGN KEY ("ORDER_ID")
	  REFERENCES "SHA"."ODER" ("ORDER_ID") ENABLE;
  ALTER TABLE "SHA"."INVOICE" ADD FOREIGN KEY ("STAFF_ID")
	  REFERENCES "SHA"."STAFF" ("STAFF_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDER_DETAILS
--------------------------------------------------------

  ALTER TABLE "SHA"."ORDER_DETAILS" ADD FOREIGN KEY ("ORDER_ID")
	  REFERENCES "SHA"."ODER" ("ORDER_ID") ENABLE;
  ALTER TABLE "SHA"."ORDER_DETAILS" ADD FOREIGN KEY ("MENU_ID")
	  REFERENCES "SHA"."MENU" ("MENU_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARTTIME
--------------------------------------------------------

  ALTER TABLE "SHA"."PARTTIME" ADD FOREIGN KEY ("STAFF_ID")
	  REFERENCES "SHA"."STAFF" ("STAFF_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "SHA"."STAFF" ADD FOREIGN KEY ("SUPERVISOR_ID")
	  REFERENCES "SHA"."STAFF" ("STAFF_ID") ENABLE;
